services:
    front:
      build:
        context: ./front
      image: "mern-frontend"
      ports:
          - "8080:80"
    back:
      build:
        context: ./back
      image: mern-backend
      container_name: backend
      ports:
          - "8081:81"
    mongo:
      image: "mongo"
      volumes:
        - mongo-data:/data/db
volumes:
  mongo-data:
